spring:
  application:
    name: bff-service

server:
  port: 8083

jwt:
  secret: ${JWT_SECRET:velourbe-secret-de-256-bits-para-jwt-firma-hmac-sha256}

# El BFF apunta a TODOS los microservicios de la plataforma.
services:
  user-auth:
    url: ${USER_AUTH_URL:http://localhost:8081}
  rental:
    url: ${RENTAL_URL:http://localhost:8082}
  payment:
    url: ${PAYMENT_URL:http://localhost:8084}
  notification:
    url: ${NOTIFICATION_URL:http://localhost:8085}
  analytics:
    url: ${ANALYTICS_URL:http://localhost:8086}
  logistics:
    url: ${LOGISTICS_URL:http://localhost:8087}
  maintenance:
    url: ${MAINTENANCE_URL:http://localhost:8088}
  support:
    url: ${SUPPORT_URL:http://localhost:8089}
  station:
    url: ${STATION_URL:http://localhost:8090}
  review:
    url: ${REVIEW_URL:http://localhost:8091}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
